/**
 * Generates recursica-tokens.css from design tokens
 */

import type { ExportingResult } from "../types";
import { TOKEN_CONFIGS, tokensToCssVariables } from "../utils/tokenToCss";
import type { TokenEntry } from "../types";

const CSS_HEADER = `/* prettier-ignore */
/* eslint-disable */
/* tslint:disable */
/*
Auto-generated by Recursica.
Do NOT edit these files directly

For more information about Recursica, go to https://recursica.com
*/

`;

export function generateTokensCss(
  tokens: Record<string, TokenEntry>,
  outputPath: string,
): ExportingResult {
  const tokensCssFilename = "recursica-tokens.css";
  const tokensCssPath = `${outputPath}/${tokensCssFilename}`;

  // Filter tokens for Mode-1 only
  const mode1Tokens: Record<string, TokenEntry> = {};
  for (const [key, token] of Object.entries(tokens)) {
    if (key.startsWith("[tokens][Mode-1]")) {
      mode1Tokens[key] = token;
    }
  }

  // Convert token names to CSS custom property format
  const cssVariables = tokensToCssVariables(
    mode1Tokens,
    TOKEN_CONFIGS.BASIC_TOKENS,
  ).join("\n");

  const tokensCssContent = `${CSS_HEADER}/* Recursica Design Tokens */
:root {
${cssVariables}
}
`;

  return {
    content: tokensCssContent,
    path: tokensCssPath,
    filename: tokensCssFilename,
  };
}


