/**
 * Generates theme CSS files (light and dark) from theme tokens
 */

import type { ExportingResult, TokenEntry } from "../types";
import { TOKEN_CONFIGS, tokensToCssVariables } from "../utils/tokenToCss";
import {
  groupLayerVariables,
  generateLayerSelector,
  generateDefaultLayerVariables,
} from "../utils/layerManagement";

const CSS_HEADER = `/* prettier-ignore */
/* eslint-disable */
/* tslint:disable */
/*
Auto-generated by Recursica.
Do NOT edit these files directly

For more information about Recursica, go to https://recursica.com
*/

`;

export function generateThemeCss(
  themes: Record<string, Record<string, TokenEntry>>,
  outputPath: string,
): ExportingResult[] {
  const themeFiles: ExportingResult[] = [];

  // Process each theme (e.g., EyePopBrand)
  for (const [themeName, themeTokens] of Object.entries(themes)) {
    // Group tokens by mode (Light, Dark, etc.)
    const tokensByMode: Record<string, Record<string, TokenEntry>> = {};

    for (const [key, token] of Object.entries(themeTokens)) {
      // Extract mode from key like "[themes][Light][...]"
      const modeMatch = key.match(/\[themes\]\[([^\]]+)\]/);
      if (modeMatch) {
        const modeName = modeMatch[1];
        if (!tokensByMode[modeName]) {
          tokensByMode[modeName] = {};
        }
        tokensByMode[modeName][key] = token;
      }
    }

    // Generate CSS file for each mode (only Light and Dark)
    const allowedModes = ["Light", "Dark"];
    for (const [modeName, modeTokens] of Object.entries(tokensByMode)) {
      // Only generate files for Light and Dark modes
      if (!allowedModes.includes(modeName)) {
        continue;
      }

      // Skip if no tokens found
      if (Object.keys(modeTokens).length === 0) {
        continue;
      }

      const themeCssFilename = `${themeName.toLowerCase()}-${modeName.toLowerCase()}-theme.css`;
      const themeCssPath = `${outputPath}/${themeCssFilename}`;
      const className = `${themeName.toLowerCase()}-${modeName.toLowerCase()}-theme`;
      const comment = `Recursica ${themeName} ${modeName} Theme`;

      // Convert theme token names to CSS custom property format
      const cssVariables = tokensToCssVariables(
        modeTokens,
        {
          ...TOKEN_CONFIGS.THEME_TOKENS,
          mode: modeName.toLowerCase(),
        },
        modeName.toLowerCase(),
      );

      // Group layer variables for layer selector generation
      const layerMap = groupLayerVariables(cssVariables);

      // Separate layer variables from other variables
      const layerVariableLines: string[] = [];
      const otherVariableLines: string[] = [];

      for (const line of cssVariables) {
        if (line.includes(`--recursica-brand-layer-layer-`)) {
          layerVariableLines.push(line);
        } else {
          otherVariableLines.push(line);
        }
      }

      // Generate default layer variables (using layer-0)
      const defaultLayerVars: string[] = [];
      const layer0Properties = layerMap.get("layer-0");
      if (layer0Properties) {
        defaultLayerVars.push(...generateDefaultLayerVariables(layer0Properties));
      }

      // Generate layer selector overrides (as separate non-nested selectors)
      const layerSelectors: string[] = [];
      const sortedLayerIds = Array.from(layerMap.keys()).sort();

      for (const layerId of sortedLayerIds) {
        const properties = layerMap.get(layerId);
        if (properties) {
          const selector = generateLayerSelector(
            layerId,
            properties,
            className,
          );
          if (selector) {
            layerSelectors.push(selector);
          }
        }
      }

      // Combine all CSS content
      const allVariables = [
        ...otherVariableLines,
        ...defaultLayerVars,
      ].join("\n");

      const layerSelectorsContent =
        layerSelectors.length > 0 ? `\n\n${layerSelectors.join("\n\n")}` : "";

      const themeCssContent = `${CSS_HEADER}/* ${comment} */
.${className} {
${allVariables}
}${layerSelectorsContent}
`;

      themeFiles.push({
        content: themeCssContent,
        path: themeCssPath,
        filename: themeCssFilename,
      });
    }
  }

  return themeFiles;
}

