/**
 * Generates a single combined recursica.css file
 * Order: tokens → themes → UI Kit
 */

import type { ExportingResult, TokenEntry } from "../types";
import { TOKEN_CONFIGS, tokensToCssVariables } from "../utils/tokenToCss";
import {
  groupLayerVariables,
  generateLayerSelector,
  generateDefaultLayerVariables,
} from "../utils/layerManagement";

const CSS_HEADER = `/* prettier-ignore */
/* eslint-disable */
/* tslint:disable */
/*
Auto-generated by Recursica.
Do NOT edit these files directly

For more information about Recursica, go to https://recursica.com
*/

`;

/**
 * Generate combined CSS with tokens, themes, and UI Kit
 */
export function generateCombinedCss(
  tokens: Record<string, TokenEntry>,
  themes: Record<string, Record<string, TokenEntry>>,
  uiKit: Record<string, TokenEntry>,
  outputPath: string,
): ExportingResult {
  const filename = "recursica.css";
  const filepath = `${outputPath}/${filename}`;

  let combinedContent = CSS_HEADER;

  // ===== 1. TOKENS =====
  combinedContent += `/* ========================================\n`;
  combinedContent += `   Recursica Design Tokens\n`;
  combinedContent += `   ======================================== */\n\n`;

  // Filter tokens for Mode-1 only
  const mode1Tokens: Record<string, TokenEntry> = {};
  for (const [key, token] of Object.entries(tokens)) {
    if (key.startsWith("[tokens][Mode-1]")) {
      mode1Tokens[key] = token;
    }
  }

  const tokensVars = tokensToCssVariables(
    mode1Tokens,
    TOKEN_CONFIGS.BASIC_TOKENS,
  ).join("\n");

  combinedContent += `:root {\n${tokensVars}\n}\n\n`;

  // ===== 2. THEMES =====
  combinedContent += `/* ========================================\n`;
  combinedContent += `   Theme Variables\n`;
  combinedContent += `   ======================================== */\n\n`;

  const themeClassNames: string[] = [];

  // Process each theme (e.g., EyePopBrand)
  for (const [themeName, themeTokens] of Object.entries(themes)) {
    // Group tokens by mode (Light, Dark, etc.)
    const tokensByMode: Record<string, Record<string, TokenEntry>> = {};

    for (const [key, token] of Object.entries(themeTokens)) {
      // Extract mode from key like "[themes][Light][...]"
      const modeMatch = key.match(/\[themes\]\[([^\]]+)\]/);
      if (modeMatch) {
        const modeName = modeMatch[1];
        if (!tokensByMode[modeName]) {
          tokensByMode[modeName] = {};
        }
        tokensByMode[modeName][key] = token;
      }
    }

    // Generate CSS for each mode (only Light and Dark)
    const allowedModes = ["Light", "Dark"];
    for (const [modeName, modeTokens] of Object.entries(tokensByMode)) {
      // Only generate for Light and Dark modes
      if (!allowedModes.includes(modeName)) {
        continue;
      }

      // Skip if no tokens found
      if (Object.keys(modeTokens).length === 0) {
        continue;
      }

      const className = `${themeName.toLowerCase()}-${modeName.toLowerCase()}-theme`;
      const comment = `${themeName} ${modeName} Theme`;

      // Convert theme token names to CSS custom property format
      const cssVariables = tokensToCssVariables(
        modeTokens,
        {
          ...TOKEN_CONFIGS.THEME_TOKENS,
          mode: modeName.toLowerCase(),
        },
        modeName.toLowerCase(),
      );

      // Group layer variables for layer selector generation
      const layerMap = groupLayerVariables(cssVariables);

      // Separate layer variables from other variables
      const otherVariableLines: string[] = [];

      for (const line of cssVariables) {
        if (!line.includes(`--recursica-brand-layer-layer-`)) {
          otherVariableLines.push(line);
        }
      }

      // Generate default layer variables (using layer-0)
      const defaultLayerVars: string[] = [];
      const layer0Properties = layerMap.get("layer-0");
      if (layer0Properties) {
        defaultLayerVars.push(...generateDefaultLayerVariables(layer0Properties));
      }

      // Generate layer selector overrides (as separate non-nested selectors)
      const layerSelectors: string[] = [];
      const sortedLayerIds = Array.from(layerMap.keys()).sort();

      for (const layerId of sortedLayerIds) {
        const properties = layerMap.get(layerId);
        if (properties) {
          const selector = generateLayerSelector(
            layerId,
            properties,
            className,
          );
          if (selector) {
            layerSelectors.push(selector);
          }
        }
      }

      // Combine all CSS content
      const allVariables = [
        ...otherVariableLines,
        ...defaultLayerVars,
      ].join("\n");

      const layerSelectorsContent =
        layerSelectors.length > 0 ? `\n\n${layerSelectors.join("\n\n")}` : "";

      themeClassNames.push(className);
      combinedContent += `/* ${comment} */\n`;
      combinedContent += `.${className} {\n${allVariables}\n}${layerSelectorsContent}\n\n`;
    }
  }

  // ===== 3. UI KIT =====
  combinedContent += `/* ========================================\n`;
  combinedContent += `   UI Kit Components\n`;
  combinedContent += `   ======================================== */\n\n`;

  // Group UI Kit tokens by mode (0 = default/layer-0, 1 = layer-1, 2 = layer-2, 3 = layer-3)
  const uiKitByMode: Record<string, Record<string, TokenEntry>> = {
    "0": {},
    "1": {},
    "2": {},
    "3": {},
  };
  for (const [key, token] of Object.entries(uiKit)) {
    const modeMatch = key.match(/\[ui-kit\]\[(\d+)\]/);
    if (modeMatch && uiKitByMode[modeMatch[1]]) {
      uiKitByMode[modeMatch[1]][key] = token;
    }
  }

  const replaceLayerRefs = (css: string): string => {
    let out = css.replace(
      /var\(--recursica-brand-layer-layer-([0-9]+|alternative-[^)]+)-/g,
      "var(--recursica-brand-layer-"
    );
    // Fix over-stripped refs: layer-surface → layer-property-surface, layer-color → layer-element-text-color
    out = out.replace(
      /var\(--recursica-brand-layer-surface\)/g,
      "var(--recursica-brand-layer-property-surface)"
    );
    out = out.replace(
      /var\(--recursica-brand-layer-color\)/g,
      "var(--recursica-brand-layer-element-text-color)"
    );
    return out;
  };

  // Base UI Kit (mode 0) under :root
  const mode0Tokens = uiKitByMode["0"];
  let uiKitBase = tokensToCssVariables(
    mode0Tokens,
    TOKEN_CONFIGS.UI_KIT_TOKENS,
  ).join("\n");
  uiKitBase = replaceLayerRefs(uiKitBase);
  combinedContent += `:root {\n${uiKitBase}\n}\n\n`;

  // Per-layer UI Kit overrides: .theme .layer-1, .layer-2, .layer-3 (mode 1, 2, 3)
  const layerModeIds: { layerId: string; mode: string }[] = [
    { layerId: "layer-1", mode: "1" },
    { layerId: "layer-2", mode: "2" },
    { layerId: "layer-3", mode: "3" },
  ];
  for (const themeClassName of themeClassNames) {
    for (const { layerId, mode } of layerModeIds) {
      const modeTokens = uiKitByMode[mode];
      if (!modeTokens || Object.keys(modeTokens).length === 0) continue;
      let layerUiKit = tokensToCssVariables(
        modeTokens,
        TOKEN_CONFIGS.UI_KIT_TOKENS,
      ).join("\n");
      layerUiKit = replaceLayerRefs(layerUiKit);
      combinedContent += `.${themeClassName} .${layerId} {\n${layerUiKit}\n}\n\n`;
    }
  }

  return {
    content: combinedContent,
    path: filepath,
    filename,
  };
}
