/**
 * Generates recursica.css from UI Kit tokens (mode 0 = light)
 */

import type { ExportingResult, TokenEntry } from "../types";
import { TOKEN_CONFIGS, tokensToCssVariables } from "../utils/tokenToCss";
// import { convertToCurrentLayer, isLayerReference } from "../utils/layerManagement";

const CSS_HEADER = `/* prettier-ignore */
/* eslint-disable */
/* tslint:disable */
/*
Auto-generated by Recursica.
Do NOT edit these files directly

For more information about Recursica, go to https://recursica.com
*/

`;

export function generateUiKitCss(
  uiKit: Record<string, TokenEntry>,
  outputPath: string,
): ExportingResult {
  const uiKitCssFilename = "recursica.css";
  const uiKitCssPath = `${outputPath}/${uiKitCssFilename}`;

  // Filter UI Kit tokens for mode 0 (light) only
  const mode0Tokens: Record<string, TokenEntry> = {};
  for (const [key, token] of Object.entries(uiKit)) {
    if (key.startsWith("[ui-kit][0]")) {
      mode0Tokens[key] = token;
    }
  }

  // Convert UI Kit token names to CSS custom property format (theme-agnostic)
  let cssVariables = tokensToCssVariables(
    mode0Tokens,
    TOKEN_CONFIGS.UI_KIT_TOKENS,
  ).join("\n");

  // Convert layer references to canonical layer var (no layer id in name)
  cssVariables = cssVariables.replace(
    /var\(--recursica-brand-layer-layer-([0-9]+|alternative-[^)]+)-/g,
    "var(--recursica-brand-layer-"
  );

  const uiKitCssContent = `${CSS_HEADER}/* Recursica UI Kit */
@import "./recursica-tokens.css";

:root {
${cssVariables}
}
`;

  return {
    content: uiKitCssContent,
    path: uiKitCssPath,
    filename: uiKitCssFilename,
  };
}


