name: Create PR from Issue

on:
  issues:
    types: [opened]

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write
  issues: write

# Allow concurrent deployments for different PRs
concurrency:
  group: "pages-issue-${{ github.event.issue.number }}"
  cancel-in-progress: true

jobs:
  create-pr-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Create Pull Request
        id: create-pr
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            
            // Extract JSON data from issue body
            const jsonMatch = issue.body.match(/```json\s*([\s\S]*?)\s*```/);
            let changeData = null;
            
            if (jsonMatch) {
              try {
                changeData = JSON.parse(jsonMatch[1]);
                console.log('Extracted change data:', changeData);
              } catch (error) {
                console.error('Failed to parse JSON from issue body:', error);
              }
            }
            
            // Create a new branch name based on the issue number
            const branchName = `issue-${issue.number}`;
            
            // Get the latest commit from the main branch
            const mainBranch = await github.rest.repos.getBranch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'main'
            });
            
            // Create the branch
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/heads/${branchName}`,
              sha: mainBranch.data.commit.sha
            });
            
            // If we have change data, create the JSON file
            if (changeData) {
              const filePath = `change-requests/change-issue-${issue.number}.json`;
              const fileContent = JSON.stringify(changeData, null, 2);
              
              await github.rest.repos.createOrUpdateFileContents({
                owner: context.repo.owner,
                repo: context.repo.repo,
                path: filePath,
                message: `Add change request file for issue #${issue.number}`,
                content: Buffer.from(fileContent).toString('base64'),
                branch: branchName
              });
              
              console.log(`Created change request file: ${filePath}`);
            }
            
            // Create the pull request
            const pr = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issue.title,
              body: `${issue.body}\n\nCloses #${issue.number}`,
              head: branchName,
              base: 'main'
            });
            
            // Add a comment to the issue linking to the PR
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              body: `PR created: #${pr.data.number}`
            });
            
            console.log(`Created PR #${pr.data.number} for issue #${issue.number}`);
            
            // Store PR number for later use
            core.setOutput('pr-number', pr.data.number);
      
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Build Storybook
        run: npm run build-storybook
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Prepare PR preview deployment
        run: |
          # Get PR number from previous step
          PR_NUMBER=${{ steps.create-pr.outputs.pr-number }}
          
          # Create a clean deployment directory
          mkdir -p deployment
          
          # Create PR-specific directory structure
          mkdir -p deployment/pr-$PR_NUMBER
          
          # Copy the latest Storybook build to PR-specific preview
          if [ -d "builds" ]; then
            # Get the most recent build (last modified)
            LATEST_BUILD=$(ls -t builds/ | head -1)
            if [ -n "$LATEST_BUILD" ]; then
              echo "Using latest build: $LATEST_BUILD"
              cp -r builds/$LATEST_BUILD/* deployment/pr-$PR_NUMBER/
            else
              echo "No builds found"
              exit 1
            fi
          else
            echo "No builds directory found"
            exit 1
          fi
          
          # Create a redirect from root to PR-specific preview
          echo '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0;url=./pr-'$PR_NUMBER'/"></head><body>Redirecting to <a href="./pr-'$PR_NUMBER'/">PR Preview</a></body></html>' > deployment/index.html
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './deployment'

      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      
      - name: Comment PR with preview URL
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = ${{ steps.create-pr.outputs.pr-number }};
            const previewUrl = `https://borderux.github.io/recursica-sandbox/pr-${prNumber}/`;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: `🎉 PR Preview deployed!\n\nView your Storybook preview here: ${previewUrl}`
            });
